// Code generated by protoc-gen-go. DO NOT EDIT.
// source: i9k.proto

package i9k

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f90e0cd4124c47f, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type StatRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatRequest) Reset()         { *m = StatRequest{} }
func (m *StatRequest) String() string { return proto.CompactTextString(m) }
func (*StatRequest) ProtoMessage()    {}
func (*StatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f90e0cd4124c47f, []int{1}
}

func (m *StatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatRequest.Unmarshal(m, b)
}
func (m *StatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatRequest.Marshal(b, m, deterministic)
}
func (m *StatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatRequest.Merge(m, src)
}
func (m *StatRequest) XXX_Size() int {
	return xxx_messageInfo_StatRequest.Size(m)
}
func (m *StatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatRequest proto.InternalMessageInfo

func (m *StatRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type StatResponse struct {
	FileName             string               `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	FileSize             int64                `protobuf:"varint,2,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	FileMode             uint32               `protobuf:"varint,3,opt,name=FileMode,proto3" json:"FileMode,omitempty"`
	FileModTime          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=FileModTime,proto3" json:"FileModTime,omitempty"`
	FileIsDirectory      bool                 `protobuf:"varint,5,opt,name=FileIsDirectory,proto3" json:"FileIsDirectory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StatResponse) Reset()         { *m = StatResponse{} }
func (m *StatResponse) String() string { return proto.CompactTextString(m) }
func (*StatResponse) ProtoMessage()    {}
func (*StatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f90e0cd4124c47f, []int{2}
}

func (m *StatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatResponse.Unmarshal(m, b)
}
func (m *StatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatResponse.Marshal(b, m, deterministic)
}
func (m *StatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatResponse.Merge(m, src)
}
func (m *StatResponse) XXX_Size() int {
	return xxx_messageInfo_StatResponse.Size(m)
}
func (m *StatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatResponse proto.InternalMessageInfo

func (m *StatResponse) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *StatResponse) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *StatResponse) GetFileMode() uint32 {
	if m != nil {
		return m.FileMode
	}
	return 0
}

func (m *StatResponse) GetFileModTime() *timestamp.Timestamp {
	if m != nil {
		return m.FileModTime
	}
	return nil
}

func (m *StatResponse) GetFileIsDirectory() bool {
	if m != nil {
		return m.FileIsDirectory
	}
	return false
}

type WritePiece struct {
	// Types that are valid to be assigned to PieceContent:
	//	*WritePiece_FileName
	//	*WritePiece_Data
	PieceContent         isWritePiece_PieceContent `protobuf_oneof:"PieceContent"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *WritePiece) Reset()         { *m = WritePiece{} }
func (m *WritePiece) String() string { return proto.CompactTextString(m) }
func (*WritePiece) ProtoMessage()    {}
func (*WritePiece) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f90e0cd4124c47f, []int{3}
}

func (m *WritePiece) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WritePiece.Unmarshal(m, b)
}
func (m *WritePiece) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WritePiece.Marshal(b, m, deterministic)
}
func (m *WritePiece) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WritePiece.Merge(m, src)
}
func (m *WritePiece) XXX_Size() int {
	return xxx_messageInfo_WritePiece.Size(m)
}
func (m *WritePiece) XXX_DiscardUnknown() {
	xxx_messageInfo_WritePiece.DiscardUnknown(m)
}

var xxx_messageInfo_WritePiece proto.InternalMessageInfo

type isWritePiece_PieceContent interface {
	isWritePiece_PieceContent()
}

type WritePiece_FileName struct {
	FileName string `protobuf:"bytes,1,opt,name=FileName,proto3,oneof"`
}

type WritePiece_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3,oneof"`
}

func (*WritePiece_FileName) isWritePiece_PieceContent() {}

func (*WritePiece_Data) isWritePiece_PieceContent() {}

func (m *WritePiece) GetPieceContent() isWritePiece_PieceContent {
	if m != nil {
		return m.PieceContent
	}
	return nil
}

func (m *WritePiece) GetFileName() string {
	if x, ok := m.GetPieceContent().(*WritePiece_FileName); ok {
		return x.FileName
	}
	return ""
}

func (m *WritePiece) GetData() []byte {
	if x, ok := m.GetPieceContent().(*WritePiece_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*WritePiece) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*WritePiece_FileName)(nil),
		(*WritePiece_Data)(nil),
	}
}

type ReadAtRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	StartOffset          uint64   `protobuf:"varint,2,opt,name=StartOffset,proto3" json:"StartOffset,omitempty"`
	Size                 uint64   `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAtRequest) Reset()         { *m = ReadAtRequest{} }
func (m *ReadAtRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAtRequest) ProtoMessage()    {}
func (*ReadAtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f90e0cd4124c47f, []int{4}
}

func (m *ReadAtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAtRequest.Unmarshal(m, b)
}
func (m *ReadAtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAtRequest.Marshal(b, m, deterministic)
}
func (m *ReadAtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAtRequest.Merge(m, src)
}
func (m *ReadAtRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAtRequest.Size(m)
}
func (m *ReadAtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAtRequest proto.InternalMessageInfo

func (m *ReadAtRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ReadAtRequest) GetStartOffset() uint64 {
	if m != nil {
		return m.StartOffset
	}
	return 0
}

func (m *ReadAtRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ReadChunk struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadChunk) Reset()         { *m = ReadChunk{} }
func (m *ReadChunk) String() string { return proto.CompactTextString(m) }
func (*ReadChunk) ProtoMessage()    {}
func (*ReadChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f90e0cd4124c47f, []int{5}
}

func (m *ReadChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadChunk.Unmarshal(m, b)
}
func (m *ReadChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadChunk.Marshal(b, m, deterministic)
}
func (m *ReadChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadChunk.Merge(m, src)
}
func (m *ReadChunk) XXX_Size() int {
	return xxx_messageInfo_ReadChunk.Size(m)
}
func (m *ReadChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadChunk.DiscardUnknown(m)
}

var xxx_messageInfo_ReadChunk proto.InternalMessageInfo

func (m *ReadChunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DirectoryEnt struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectoryEnt) Reset()         { *m = DirectoryEnt{} }
func (m *DirectoryEnt) String() string { return proto.CompactTextString(m) }
func (*DirectoryEnt) ProtoMessage()    {}
func (*DirectoryEnt) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f90e0cd4124c47f, []int{6}
}

func (m *DirectoryEnt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectoryEnt.Unmarshal(m, b)
}
func (m *DirectoryEnt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectoryEnt.Marshal(b, m, deterministic)
}
func (m *DirectoryEnt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectoryEnt.Merge(m, src)
}
func (m *DirectoryEnt) XXX_Size() int {
	return xxx_messageInfo_DirectoryEnt.Size(m)
}
func (m *DirectoryEnt) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectoryEnt.DiscardUnknown(m)
}

var xxx_messageInfo_DirectoryEnt proto.InternalMessageInfo

func (m *DirectoryEnt) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DirectoryEnt) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type DirectoryList struct {
	Results              []*DirectoryEnt `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DirectoryList) Reset()         { *m = DirectoryList{} }
func (m *DirectoryList) String() string { return proto.CompactTextString(m) }
func (*DirectoryList) ProtoMessage()    {}
func (*DirectoryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f90e0cd4124c47f, []int{7}
}

func (m *DirectoryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectoryList.Unmarshal(m, b)
}
func (m *DirectoryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectoryList.Marshal(b, m, deterministic)
}
func (m *DirectoryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectoryList.Merge(m, src)
}
func (m *DirectoryList) XXX_Size() int {
	return xxx_messageInfo_DirectoryList.Size(m)
}
func (m *DirectoryList) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectoryList.DiscardUnknown(m)
}

var xxx_messageInfo_DirectoryList proto.InternalMessageInfo

func (m *DirectoryList) GetResults() []*DirectoryEnt {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*StatRequest)(nil), "StatRequest")
	proto.RegisterType((*StatResponse)(nil), "StatResponse")
	proto.RegisterType((*WritePiece)(nil), "WritePiece")
	proto.RegisterType((*ReadAtRequest)(nil), "ReadAtRequest")
	proto.RegisterType((*ReadChunk)(nil), "ReadChunk")
	proto.RegisterType((*DirectoryEnt)(nil), "DirectoryEnt")
	proto.RegisterType((*DirectoryList)(nil), "DirectoryList")
}

func init() { proto.RegisterFile("i9k.proto", fileDescriptor_1f90e0cd4124c47f) }

var fileDescriptor_1f90e0cd4124c47f = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xcd, 0xd6, 0x8a, 0x3f, 0x46, 0x92, 0x0b, 0x4b, 0x0f, 0x42, 0x14, 0xa2, 0xa8, 0x85, 0xe8,
	0xb4, 0x01, 0x17, 0x4a, 0x0b, 0xbd, 0xa4, 0x49, 0x4a, 0x0a, 0xfd, 0x30, 0xeb, 0x40, 0xe9, 0x71,
	0x93, 0x8c, 0x9d, 0x25, 0x92, 0xd6, 0xd5, 0x8e, 0x0f, 0xe9, 0xaf, 0xe9, 0xef, 0xe9, 0xaf, 0x2a,
	0x5a, 0x59, 0x8a, 0x1c, 0x4a, 0x6e, 0xf3, 0x76, 0x66, 0x9e, 0xe6, 0x3d, 0x3d, 0x98, 0xe8, 0xf7,
	0x77, 0x62, 0x5d, 0x19, 0x32, 0xf1, 0xc1, 0xca, 0x98, 0x55, 0x8e, 0xc7, 0x0e, 0x5d, 0x6d, 0x96,
	0xc7, 0xa4, 0x0b, 0xb4, 0xa4, 0x8a, 0x75, 0x33, 0x90, 0x8e, 0x60, 0xff, 0xbc, 0x58, 0xd3, 0x7d,
	0x7a, 0x08, 0xfe, 0x82, 0x14, 0x49, 0xfc, 0xb5, 0x41, 0x4b, 0x9c, 0x83, 0x37, 0x57, 0x74, 0x1b,
	0xb1, 0x84, 0x65, 0x13, 0xe9, 0xea, 0xf4, 0x2f, 0x83, 0xa0, 0x99, 0xb1, 0x6b, 0x53, 0x5a, 0xe4,
	0x31, 0x8c, 0x3f, 0xe9, 0x1c, 0xbf, 0xa9, 0x02, 0xb7, 0x83, 0x1d, 0x6e, 0x7b, 0x0b, 0xfd, 0x1b,
	0xa3, 0x67, 0x09, 0xcb, 0x06, 0xb2, 0xc3, 0x6d, 0xef, 0xab, 0xb9, 0xc1, 0x68, 0x90, 0xb0, 0x2c,
	0x94, 0x1d, 0xe6, 0x1f, 0xc0, 0xdf, 0xd6, 0x97, 0xba, 0xc0, 0xc8, 0x4b, 0x58, 0xe6, 0xcf, 0x62,
	0xd1, 0xe8, 0x10, 0xad, 0x0e, 0x71, 0xd9, 0xea, 0x90, 0xfd, 0x71, 0x9e, 0xc1, 0xf3, 0x1a, 0x7e,
	0xb6, 0x67, 0xba, 0xc2, 0x6b, 0x32, 0xd5, 0x7d, 0xb4, 0x9f, 0xb0, 0x6c, 0x2c, 0x1f, 0x3f, 0xa7,
	0x73, 0x80, 0x1f, 0x95, 0x26, 0x9c, 0x6b, 0xbc, 0x46, 0xfe, 0xf2, 0xb1, 0x92, 0x8b, 0xbd, 0x9e,
	0x96, 0x17, 0xe0, 0x9d, 0x29, 0x52, 0x4e, 0x47, 0x70, 0xb1, 0x27, 0x1d, 0xfa, 0x38, 0x85, 0xc0,
	0x2d, 0x9f, 0x9a, 0x92, 0xb0, 0xa4, 0xf4, 0x27, 0x84, 0x12, 0xd5, 0xcd, 0xc9, 0x53, 0x1e, 0xf2,
	0xc4, 0xd9, 0x5c, 0xd1, 0xf7, 0xe5, 0xd2, 0x22, 0x39, 0x46, 0x4f, 0xf6, 0x9f, 0xea, 0x2d, 0x67,
	0xda, 0xc0, 0xb5, 0x5c, 0x9d, 0x1e, 0xc0, 0xa4, 0xa6, 0x3e, 0xbd, 0xdd, 0x94, 0x77, 0xf5, 0x80,
	0xbb, 0xa6, 0xa6, 0x0d, 0x9a, 0x5b, 0xd2, 0xb7, 0x10, 0x74, 0xd2, 0xce, 0xcb, 0xff, 0x7f, 0xba,
	0x25, 0x6e, 0xfe, 0x46, 0x43, 0xfc, 0x0e, 0xc2, 0x6e, 0xef, 0x8b, 0xb6, 0xc4, 0x8f, 0x60, 0x24,
	0xd1, 0x6e, 0x72, 0xb2, 0x11, 0x4b, 0x06, 0x99, 0x3f, 0x0b, 0x45, 0x9f, 0x58, 0xb6, 0xdd, 0xd9,
	0x1f, 0x06, 0xa3, 0x05, 0x99, 0x4a, 0xad, 0x90, 0xbf, 0x02, 0xaf, 0xce, 0x05, 0x0f, 0x44, 0x2f,
	0x42, 0x71, 0x28, 0x76, 0xc2, 0x72, 0x08, 0x63, 0x67, 0xf8, 0x49, 0x9e, 0x73, 0x5f, 0x3c, 0x78,
	0x1f, 0x0f, 0x85, 0x4b, 0x60, 0xc6, 0xf8, 0x6b, 0x18, 0x36, 0x0e, 0xf2, 0xa9, 0xd8, 0xb1, 0x32,
	0x06, 0xf1, 0xa0, 0xff, 0x08, 0xc2, 0xfa, 0xd4, 0xee, 0x2c, 0xbe, 0x25, 0x88, 0xa7, 0x62, 0x47,
	0xcb, 0xd5, 0xd0, 0xa5, 0xe5, 0xcd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x51, 0x81, 0xb2,
	0x10, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	WriteAll(ctx context.Context, opts ...grpc.CallOption) (Storage_WriteAllClient, error)
	ReadAt(ctx context.Context, in *ReadAtRequest, opts ...grpc.CallOption) (*ReadChunk, error)
	ListDirectory(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DirectoryList, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, "/Storage/Stat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) WriteAll(ctx context.Context, opts ...grpc.CallOption) (Storage_WriteAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Storage_serviceDesc.Streams[0], "/Storage/WriteAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageWriteAllClient{stream}
	return x, nil
}

type Storage_WriteAllClient interface {
	Send(*WritePiece) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type storageWriteAllClient struct {
	grpc.ClientStream
}

func (x *storageWriteAllClient) Send(m *WritePiece) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storageWriteAllClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageClient) ReadAt(ctx context.Context, in *ReadAtRequest, opts ...grpc.CallOption) (*ReadChunk, error) {
	out := new(ReadChunk)
	err := c.cc.Invoke(ctx, "/Storage/ReadAt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) ListDirectory(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DirectoryList, error) {
	out := new(DirectoryList)
	err := c.cc.Invoke(ctx, "/Storage/ListDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	WriteAll(Storage_WriteAllServer) error
	ReadAt(context.Context, *ReadAtRequest) (*ReadChunk, error)
	ListDirectory(context.Context, *Empty) (*DirectoryList, error)
}

// UnimplementedStorageServer can be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (*UnimplementedStorageServer) Stat(ctx context.Context, req *StatRequest) (*StatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (*UnimplementedStorageServer) WriteAll(srv Storage_WriteAllServer) error {
	return status.Errorf(codes.Unimplemented, "method WriteAll not implemented")
}
func (*UnimplementedStorageServer) ReadAt(ctx context.Context, req *ReadAtRequest) (*ReadChunk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAt not implemented")
}
func (*UnimplementedStorageServer) ListDirectory(ctx context.Context, req *Empty) (*DirectoryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDirectory not implemented")
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_WriteAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServer).WriteAll(&storageWriteAllServer{stream})
}

type Storage_WriteAllServer interface {
	SendAndClose(*Empty) error
	Recv() (*WritePiece, error)
	grpc.ServerStream
}

type storageWriteAllServer struct {
	grpc.ServerStream
}

func (x *storageWriteAllServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storageWriteAllServer) Recv() (*WritePiece, error) {
	m := new(WritePiece)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Storage_ReadAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).ReadAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/ReadAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).ReadAt(ctx, req.(*ReadAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_ListDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).ListDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/ListDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).ListDirectory(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stat",
			Handler:    _Storage_Stat_Handler,
		},
		{
			MethodName: "ReadAt",
			Handler:    _Storage_ReadAt_Handler,
		},
		{
			MethodName: "ListDirectory",
			Handler:    _Storage_ListDirectory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteAll",
			Handler:       _Storage_WriteAll_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "i9k.proto",
}
